name: Build LibMultiSense

on:
  push:
    branches:
      - master
  release:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref_name }}-build
      cancel-in-progress: ${{ github.ref_name != 'main' }}
    steps:
      - id: setup
        run: |
          sudo apt-get install libgtest-dev nlohmann-json3-dev -y
      - uses: actions/checkout@v4
      - id: build-release
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_JSON_SERIALIZATION=ON -DBUILD_LEGACY_API=OFF -DCMAKE_INSTALL_PREFIX=install-release
          cmake --build build -j "$(nproc)"
          make -C build test
          cmake --install build
      - id: build-debug
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_JSON_SERIALIZATION=ON -DBUILD_LEGACY_API=OFF -DCMAKE_INSTALL_PREFIX=install-debug
          cmake --build build -j "$(nproc)"
          make -C build test
          cmake --install build

  buildmacos:
    name: build for macos
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - id: build-release
      run: |
          cmake -B ${{github.workspace}}/build -DBUILD_LEGACY_API=OFF -DBUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j "$(nproc)"
    - id: build-debug
      run: |
          cmake -B ${{github.workspace}}/build -DBUILD_LEGACY_API=OFF -DBUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -j "$(nproc)"

  buildwindows:
    name: build for windows
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - id: build-release
      run: |
          cmake -B ${{github.workspace}}/build -DBUILD_LEGACY_API=OFF -DBUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release
          cmake --build ${{github.workspace}}/build --config Release --target install -- /m:10
    - id: build-debug
      run: |
          cmake -B ${{github.workspace}}/build -DBUILD_LEGACY_API=OFF -DBUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Debug
          cmake --build ${{github.workspace}}/build --config Debug --target install -- /m:10


